import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Modal from '@/components/modals/Modal';
import ClientOnly from '@/components/ClientOnly';
import { Navbar } from '@/components/navbar/Navbar';
import RegisterModal from '@/components/modals/RegisterModal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
            <ClientOnly>
                <RegisterModal />
                <Navbar />
            </ClientOnly>
        </html>
    );
}
